# Generated by Django 2.0.7 on 2018-08-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('sn', models.IntegerField()),
                ('imei', models.IntegerField()),
                ('eth_mac', models.CharField(max_length=12)),
                ('wifi_mac', models.CharField(max_length=12)),
                ('temper', models.IntegerField()),
                ('adc1', models.SmallIntegerField()),
                ('adc2', models.SmallIntegerField()),
                ('rs485', models.SmallIntegerField()),
                ('lora1', models.SmallIntegerField()),
                ('lora2', models.SmallIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='display_msg',
        ),
    ]
