# Generated by Django 2.0.7 on 2018-08-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180802_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='dac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('data', models.SmallIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='publish_dac',
        ),
        migrations.DeleteModel(
            name='publish_rtc',
        ),
    ]
