# Generated by Django 2.0.7 on 2018-08-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180803_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dac',
            options={'ordering': ['time']},
        ),
        migrations.AlterModelOptions(
            name='msg',
            options={'ordering': ['time']},
        ),
        migrations.AlterField(
            model_name='dac',
            name='data',
            field=models.FloatField(),
        ),
    ]
